apiVersion: v1
kind: Pod
metadata:
  name: nginx # this is pod name
  labels:
    project: roboshop
    environment: dev
    app: nginx
spec:
  containers:
  - name: nginx # this is container name
    image: nginx:1.14.2 # if not availbe in local get it from docker hub
    ports:
    - containerPort: 80
