apiVersion: v1
kind: Pod
metadata:
  name: multi-container
  labels:
    project: roboshop
spec:
  containers:
  - name: nginx # this is container 1
    image: nginx
  - name: almalinux # this is container 2
    image: almalinux:9
    command: ["sleep", "1000"] # we are giving command to k8 to runt this container for 100sec
    