apiVersion: v1
kind: Pod
metadata:
  name: annotations
  labels:
    project: roboshop
  annotations:
    imageregistry: "https://hub.docker.com/"
    jenkins-build-url: "https://jenkins.joindevops.com/build/roboshop/job/2"
spec:
  containers:
  - name: nginx
    image: nginx


# annotations are used to the resources external to yhe kubernetes cluster, like jenkins, dockerhub, gitlab etc. we can add any number of annotations to the resources. we can use this annotations to get the information about the resource from external tools.