apiVersion: v1
kind: Pod
metadata:
  name: resources
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      requests: # soft limit
        cpu: "100m" # 1000m is 1cpu
        memory: "128Mi"
      limits: # hard limit
        cpu: "150m"
        memory: "256Mi"


# we are using resource requests and limits, 
#containers can consume resources dynamically. if resources are locked containers keep using more and more resources. other conatainers in the host cant get resources

# resources
# ===========
# we should limit resources always to containers/pod

# cpu and ram/memory